name = "BlackScholesGreeks"
uuid = "4f6d5192-b49c-4e8b-a56c-ea975a6ab39f"
authors = ["Yefeng Wang"]
version = "0.1.0"

[compat]
julia = "1.6.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
